[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  REACT_APP_SITE_URL = "https://wedding-invitation-dn.netlify.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
